name: "Ansible"

on:
  push:
    branches:
      - main
      - success_complete
  pull_request:

jobs:
  ansible:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Ansible validate yaml syntax 123
        run: "ansible-playbook --version"
